"""Initial Migration

Revision ID: 127cf0a7e0a9
Revises: d3416e8c906c
Create Date: 2020-10-27 18:42:27.637977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127cf0a7e0a9'
down_revision = 'd3416e8c906c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secure_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secure_password')
    # ### end Alembic commands ###
